export default icons = {
    updateProfile:  require('../assets/icons/ui-elements/user-profile.png'),
    chat: require('../assets/icons/ui-elements/chat.png'),
    event: require('../assets/icons/ui-elements/event.png'),
    logout: require('../assets/icons/ui-elements/logout.png'),
    changePassword: require('../assets/icons/ui-elements/padlock.png'),
    next: require('../assets/icons/ui-elements/next.png'),
    arrowhead: require('../assets/icons/ui-elements/arrowhead.png'),
    hide: require('../assets/icons/ui-elements/hide.png'),
    show: require('../assets/icons/ui-elements/seen.png'),
    filter: require('../assets/icons/ui-elements/filter.png'),
    search: require('../assets/icons/ui-elements/search.png'),
    smartphone: require('../assets/icons/ui-elements/smartphone.png'),
    welcome: require('../assets/icons/sticker/welcome.png'),
    editAvatar: require('../assets/icons/ui-elements/pen-circle.png'),
    task: require('../assets/icons/ui-elements/to-do-list.png'),
    add: require('../assets/icons/ui-elements/plus.png'),
    delete: require('../assets/icons/ui-elements/recycle-bin.png'),
    event: require('../assets/icons/ui-elements/party.png'),

    homeTab: require('../assets/icons/tabbar/home.png'),
    searchTab: require('../assets/icons/tabbar/search.png'),
    createTab: require('../assets/icons/tabbar/create.png'),
    notificationTab: require('../assets/icons/tabbar/bell.png'),
    menuTab: require('../assets/icons/tabbar/user.png'),
    homeTab2: require('../assets/icons/tabbar/home-2.png'),
    notificationTab2: require('../assets/icons/tabbar/bell-2.png'),
    menuTab2: require('../assets/icons/tabbar/user-2.png'),
}